```yaml
name: deploy-and-notify

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: ./build.sh

    - name: Deploy to testing environment
      # Add your deployment steps here

    - name: Notify Teams
      # Add Microsoft Teams notification steps here
```
