


name: deploy-multi-env.yml

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - name: Checkout code from main branch
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install boto3
      - name: deploy_staging
        if: github.event.branch == 'staging'
        needs: deploy
        steps:
          - name: Use AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_STAGING_KEY }}
              aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET }}
              aws-region: us-east-1
          - name: Configure environment variables
            run: boto3 configure set AWS_ACCESS_KEY_ID ${{ secrets.AWS_STAGING_KEY }} && boto3 configure set AWS_SECRET_ACCESS_KEY ${{ secrets.AWS_STAGING_SECRET }}
      - name: deploy_production
        if: github.event.branch == 'master'
        needs: deploy
        steps:
          - name: Use AWS credentials
            uses: aws-actions