

name: branch-protection.yml
on: [push]
jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for code changes
        run: git diff --quiet || (echo "Code changes detected. Running job." && exit 1)
        shell: bash
      - name: Enforce code coverage report
        run: npm run coverage
      - name: Verify code linting and unit tests
        run: npm run lint && npm run test
      - name: Complete job
        run: echo "Job completed successfully."