


name: branch-protection.yml
on:
  push:
    branches: [main]
jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for code changes
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
      - name: Enforce code coverage report
        if: ${{ steps.check_code_changes.outputs.has_changes == 'true' }}
        run: |
          npm run code-coverage
      - name: Verify code linting and unit tests
        if: ${{ steps.check_code_changes.outputs.has_changes == 'true' }}
        run: |
          npm run lint
          npm run test
      - name: Complete job
        if: ${{ steps.check_code_changes.outputs.has_changes == 'true' }}
        run: |
          echo "Job completed successfully!"