

name: branch-protection.yml
on:
  push:
    branches: [main]
jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    container:
      image: Node.js 20
    steps:
      - name: Check for code changes
        run: git diff --quiet --exit-code || echo "There are code changes."
      - name: Enforce code coverage report
        run: npm run coverage
      - name: Verify code linting and unit tests
        run: npm run lint && npm run test
      - name: Complete job
        run: echo "Job completed successfully."