


name: branch-protection.yml
on:
  push:
    branches: [main]
jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for code changes
        uses: actions/github-script@v3
        with:
          script: |
            if (github.context.payload.commits.length > 0) {
              console.log('Code changes detected.');
            } else {
              console.log('No code changes found.');
              return;
            }
      - name: Enforce code coverage report
        run: enforce-coverage-report.sh
      - name: Verify code linting and unit tests
        run: verify-linting-and-unit-tests.sh
      - name: Complete job
        run: complete-job.sh