


name: branch-protection.yml

on:
  push:
    branches:
      - main

jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Check for code changes
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > changes.txt

      - name: Enforce code coverage report
        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
        run: |
          npm install
          npm run coverage

      - name: Verify code linting and unit tests
        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
        run: |
          npm install
          npm run lint
          npm test

      - name: Complete job
        if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
        run: |
          echo "All jobs completed successfully."

      - name: Set up job
        if: ${{ steps.check_changes.outputs.has_changes == 'false' }}
       