

name: branch-protection.yml
on:
  push:
    branches: [main]
jobs:
  enforce-branch-rules:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v2
      - name: Check for code changes
        run: git diff --quiet || exit 1
      - name: Enforce code coverage report
        run: coverage run tests.py
      - name: Verify code linting and unit tests
        run: npm run lint && npm run test
      - name: Complete job
        run: echo "Job completed successfully."